### ISSUE TITLE
there already have your script link i cant sell your script

### ISSUE THREAD

**Issue by rlk-subscription** [MaDHouSe79/Scammers-Active#1]

**Comment by MaDHouSe79** [comment]
Remove the scripts from your account cause you did not make that.
you put your own name as creator and that just false.

**Comment by rlk-subscription** [comment]
ok i will remove it now

**Comment by rlk-subscription** [comment]
now you can delete your scammer post for help of me iam not a scammer btw already deleted your script

**Comment by MaDHouSe79** [comment]
Thank you, But it's a shame you did this, you could have just linked my scripts and then I wouldn't have had a problem with it, but you put your own name under it as if you made it, and then ask for support money for something you didn't make yourself, that's just scamming other people while they get free support from me.

Thank you for deleting the scripts.
